wandb_version: 1

timesteps_per_batch:
  desc: null
  value: 100000
max_timesteps_per_episode:
  desc: null
  value: 10000
gamma:
  desc: null
  value: 0.95
n_updates_per_iteration:
  desc: null
  value: 5
clip:
  desc: null
  value: 0.2
lr:
  desc: null
  value: 0.005
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724447929
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.10.0
      5: 0.17.7
      8:
      - 3
      - 5
      13: windows-amd64
